import { mkdirSync, readdirSync, writeFileSync, readFileSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { compileFromFile } from 'json-schema-to-typescript';
import { fileURLToPath } from 'url';

const OpenSpaceDirectory = process.argv[2];

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outputDir = resolve(__dirname, '../src/types/generated');

if (!OpenSpaceDirectory) {
  console.error(
    'Provide a path to the schema directory in the OpenSpace/support/types folder'
  );
  console.log('Usage: npm run generate-types-topics <inputDir>');
  process.exit(1);
}

const resolvedInputDir = resolve(OpenSpaceDirectory);

// Ensure output folder exists
mkdirSync(outputDir, { recursive: true });

/**
 * Generate a correspondig .d.ts type file for each .json type schema found
 */
async function generateTypesForTopics() {
  const files = readdirSync(resolvedInputDir).filter((f) => f.endsWith('.json'));

  for (const file of files) {
    const inputPath = join(resolvedInputDir, file);
    const outputPath = join(outputDir, file.replace('.json', '.d.ts'));

    try {
      const ts = await compileFromFile(inputPath, {
        additionalProperties: false,
        bannerComment:
          '/**\n' +
          '* This file was automatically generated by json-schema-to-typescript.\n' +
          '* DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file, \n' +
          '* and run json-schema-to-typescript to regenerate this file.\n*/',
        style: {
          printWidth: 90,
          tabWidth: 2,
          singleQuote: true,
          trailingComma: 'none',
          endOfLine: 'auto'
        }
      });

      writeFileSync(outputPath, ts);
      console.log(`Generated: ${outputPath}`);
    } catch (err) {
      console.error(`Failed: ${file}`, err.message);
    }
  }
}

function generateIndexFile() {
  const files = readdirSync(outputDir).filter(
    (f) => f.endsWith('.d.ts') && f !== 'index.d.ts'
  );

  const imports = [];
  const topicNames = [];

  for (const file of files) {
    const filePath = join(outputDir, file);
    const content = readFileSync(filePath, 'utf-8');

    // Get all the interfaces in the file
    const interfaceMatches = [...content.matchAll(/export interface (\w+)/g)];

    for (const match of interfaceMatches) {
      // Get the name of the interface
      const name = match[1];
      if (!name.endsWith('Topic')) {
        continue;
      }

      // Slice from this interface onward
      const startIndex = match.index;
      const rest = content.slice(startIndex);

      // Check if this interface contains topicId
      if (!/topicId\s*:/.test(rest)) {
        continue;
      }

      const importPath = `./${file.replace('.d.ts', '')}`;
      imports.push(`import { ${name} } from '${importPath}';`);
      topicNames.push(name);
    }
  }

  const union =
    topicNames.length > 0
      ? `export type AllTopics =\n  | ${topicNames.join('\n  | ')};\n`
      : '';

  const output =
    `// AUTO-GENERATED FILE — DO NOT EDIT\n\n${imports.join('\n')}\n\n` + union;

  const indexPath = join(outputDir, 'index.d.ts');

  writeFileSync(indexPath, output);

  console.log(`Generated: ${indexPath}`);
}

async function run() {
  await generateTypesForTopics();
  generateIndexFile();
}

run();
