import { mkdirSync, readdirSync, writeFileSync, readFileSync } from 'fs';
import { resolve, join, dirname } from 'path';
import { compileFromFile } from 'json-schema-to-typescript';
import { fileURLToPath } from 'url';

const OpenSpaceDirectory = process.argv[2];

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const outputDir = resolve(__dirname, '../src/types/generated');

if (!OpenSpaceDirectory) {
  console.error(
    'Provide a path to the schema directory in the OpenSpace/support/types folder'
  );
  console.log('Usage: npm run generate-types-topics <inputDir>');
  process.exit(1);
}

const resolvedInputDir = resolve(OpenSpaceDirectory);

// Ensure output folder exists
mkdirSync(outputDir, { recursive: true });

const Style = {
  printWidth: 90,
  tabWidth: 2,
  singleQuote: true,
  trailingComma: 'none',
  endOfLine: 'auto'
};

const BannerComment =
  '/**\n' +
  ' * This file was automatically generated by json-schema-to-typescript.\n' +
  ' * DO NOT MODIFY IT BY HAND. Instead, modify the source JSON Schema file,\n' +
  ' * and run json-schema-to-typescript to regenerate this file.\n */';

/**
 * Extracts all type names defined in the $defs of a JSON schema file.
 */
function extractDefNames(schemaPath) {
  const schema = JSON.parse(readFileSync(schemaPath, 'utf-8'));
  return Object.keys(schema['$defs'] ?? {});
}

/**
 * Recursively walks a parsed JSON value checking for $ref strings that point to
 * properties.json.
 */
function containsPropertiesRef(value) {
  if (typeof value === 'string') {
    return value.startsWith('properties.json');
  }
  if (Array.isArray(value)) {
    return value.some(containsPropertiesRef);
  }
  if (typeof value === 'object' && value !== null) {
    return Object.values(value).some(containsPropertiesRef);
  }
  return false;
}

/**
 * Checks whether a schema file references properties.json at all.
 */
function referencesPropertiesSchema(filePath) {
  const schema = JSON.parse(readFileSync(filePath, 'utf-8'));
  return containsPropertiesRef(schema);
}

/**
 * Post-processes a compiled topic .ts file to replace re-emitted property type
 * declarations with a targeted import from './properties'.
 *
 * For each type name in `propertyDefNames` that appears as an export declaration
 * in the compiled output, we strip the declaration and collect the name for import.
 *
 * Note: block-matching patterns assume well-formed json-schema-to-typescript output
 * where interface/type bodies do not contain closing braces on their own line
 * before the actual end of the block. This holds for all generated output in practice.
 */
function replacePropertyDeclarationsWithImport(compiledOutput, propertyDefNames) {
  let output = compiledOutput;

  // Remove full exported declarations like `export interface DMat3Property { ... }` that
  // would be re-emitted from properties.ts
  for (const name of propertyDefNames) {
    // Match export interface, export type alias, or export enum for this type name.
    const interfacePattern = new RegExp(
      `export interface ${name}\\s*\\{[\\s\\S]*?\\}\\n`,
      'g'
    );
    const typePattern = new RegExp(
      `export type ${name}\\s*=[\\s\\S]*?;\n(?=\\n|export|/\\*\\*)`,
      'g'
    );
    // const typePattern = new RegExp(`export type ${name}\\s*=[\\s\\S]*?;\\n`, 'g');
    const enumPattern = new RegExp(`export enum ${name}\\s*\\{[\\s\\S]*?\\}\\n`, 'g');

    output = output
      .replace(interfacePattern, '')
      .replace(typePattern, '')
      .replace(enumPattern, '');
  }

  // After removing declarations we're left with the actual usage of these types. We only
  // want to import the types that are used in this file
  const actuallyUsedTypes = propertyDefNames.filter((name) => {
    const usagePattern = new RegExp(`\\b${name}\\b`);
    return usagePattern.test(output);
  });

  // We may end up in a situation where a topic schema references properties.json but
  // doesn't use any of the types defined in it, for example in nested interfaces
  if (actuallyUsedTypes.length === 0) {
    return compiledOutput;
  }

  // Cleanup excess newlines
  output = output.replace(/\n{2,}/g, '\n');
  // Inject import after the banner comment closing */
  const importLine = `import type { ${actuallyUsedTypes.join(', ')} } from './properties';`;
  output = output.replace(/(\*\/\n)/, `$1\n${importLine}\n\n`);

  return output;
}

/**
 * Generates properties.ts from properties.json. Uses unreachableDefinitions: true
 * so all $defs are emitted even though properties.json has no top-level contract.
 */
async function generatePropertiesTypes() {
  const propertiesSchemaPath = join(resolvedInputDir, 'properties.json');
  const outputPath = join(outputDir, 'properties.ts');

  try {
    const ts = await compileFromFile(propertiesSchemaPath, {
      additionalProperties: false,
      enableConstEnums: false,
      unreachableDefinitions: true,
      bannerComment: BannerComment,
      style: Style
    });

    writeFileSync(outputPath, ts);
    console.log(`Generated: ${outputPath}`);
  } catch (err) {
    console.error('Failed to generate properties types', err.message);
  }
}

/**
 * Generates a .ts type file for each topic .json schema. Topics referencing
 * properties.json are post-processed: re-emitted property type
 * declarations are stripped and replaced with a targeted import from './properties'.
 * All locally defined types in the topic schema are preserved untouched.
 */
async function generateTypesForTopics(propertyDefNames) {
  const files = readdirSync(resolvedInputDir).filter((f) => f.endsWith('topic.json'));

  for (const file of files) {
    const inputPath = join(resolvedInputDir, file);
    const outputPath = join(outputDir, file.replace('.json', '.ts'));
    // @TODO (anden88 2026-05-04): We could perhaps improve this by not post-process all
    // topics, however, if topics redefine a type declaration like JsonValue we need a
    // better method of finding duplicate type names.
    const needsPostProcess = true; //referencesPropertiesSchema(inputPath);

    try {
      let ts = await compileFromFile(inputPath, {
        additionalProperties: false,
        enableConstEnums: false,
        bannerComment: BannerComment,
        style: Style
      });

      if (needsPostProcess) {
        ts = replacePropertyDeclarationsWithImport(ts, propertyDefNames);
      }

      writeFileSync(outputPath, ts);
      console.log(`Generated: ${outputPath}`);
    } catch (err) {
      console.error(`Failed: ${file}`, err.message);
    }
  }
}

/**
 * Generate an index.ts file that exports a union type of all the generated topic types
 */
function generateIndexFile() {
  const schemaFiles = readdirSync(resolvedInputDir).filter((f) =>
    f.endsWith('topic.json')
  );

  const imports = [];
  const reExports = [];
  const topicNames = [];

  // Property types are the foundation. Re-exported first so consuming code can import
  // AnyProperty, PropertyOwner etc. from the index
  reExports.push(`export * from './properties';`);
  reExports.push(`export * from './openspacelualibrary';`);

  // Re-export topic types and collect topic names for the union
  for (const file of schemaFiles) {
    const schemaPath = join(resolvedInputDir, file);
    const schema = JSON.parse(readFileSync(schemaPath, 'utf-8'));
    const tsFile = file.replace('.json', '.ts');
    const modulePath = `./${tsFile.replace('.ts', '')}`;

    // Always re-export everything from every genrated topic file
    reExports.push(`export * from '${modulePath}';`);

    // Only add to AllTopics union if the schema follows the topic contract
    if (
      typeof schema.title === 'string' &&
      schema.title.endsWith('Topic') &&
      schema.properties?.topicId !== undefined
    ) {
      const interfaceName = schema.title; // e.g., "LuaScriptTopic
      imports.push(`import { ${interfaceName} } from './${tsFile.replace('.ts', '')}';`);
      topicNames.push(interfaceName);
    }
  }

  if (topicNames.length === 0) {
    throw new Error(
      'No valid topic types found. Ensure the JSON schemas have a title ending with ' +
        '"Topic" and include a "topicId" property.'
    );
  }
  const union = `export type AllTopics =\n  | ${topicNames.join('\n  | ')};\n`;

  const output =
    `// AUTO-GENERATED FILE — DO NOT EDIT\n\n` +
    `${reExports.join('\n')}\n\n` +
    `${imports.join('\n')}\n\n` +
    union;

  const indexPath = join(outputDir, 'index.ts');
  writeFileSync(indexPath, output);
  console.log(`Generated: ${indexPath}`);
}

async function run() {
  // Generate properties.ts first since topic post-processing depends on its $def names
  await generatePropertiesTypes();

  // Read def names directly from the JSON
  const propertiesSchemaPath = join(resolvedInputDir, 'properties.json');
  const propertyDefNames = extractDefNames(propertiesSchemaPath);

  await generateTypesForTopics(propertyDefNames);
  generateIndexFile();
}

run();
